import { useEffect, useMemo, useState } from 'react';
import { createWorker } from 'tesseract.js';
import { parseChineseTextToCards } from '../lib/chineseImport.js';
import { generateLessonFlashcards } from '../lib/flashcardGeneration.js';
import SuccessBurst from './SuccessBurst.jsx';
import TokenButton from './ui/TokenButton.jsx';

function isHanzi(char) {
  return /[\u3400-\u9fff\uf900-\ufaff]/u.test(char);
}

function keepChineseChars(input) {
  const chars = Array.from(String(input || ''));
  return chars
    .map((char) => (isHanzi(char) || char === '\n' ? char : ''))
    .join('')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function uniqueTokens(input) {
  const cards = parseChineseTextToCards(input);
  return cards.map((card) => card.hanzi).filter(Boolean);
}

export default function OcrLessonBuilder({
  lessons = [],
  onCreateLesson,
  onUpdateLesson,
  onClose,
  onSuccess,
}) {
  const [selectedLessonId, setSelectedLessonId] = useState('');
  const [lessonTitle, setLessonTitle] = useState('');
  const [description, setDescription] = useState('');
  const [notes, setNotes] = useState('');
  const [rawOcrText, setRawOcrText] = useState('');
  const [editedText, setEditedText] = useState('');
  const [pinyinToggles, setPinyinToggles] = useState({});
  const [status, setStatus] = useState('');
  const [error, setError] = useState('');
  const [successTick, setSuccessTick] = useState(0);
  const [isScanning, setIsScanning] = useState(false);

  const selectedLesson = useMemo(
    () => lessons.find((lesson) => lesson.id === selectedLessonId) || null,
    [lessons, selectedLessonId],
  );

  const tokens = useMemo(() => uniqueTokens(editedText), [editedText]);

  useEffect(() => {
    const storedRaw = sessionStorage.getItem('wisemama-ocr-raw');
    const storedEdited = sessionStorage.getItem('wisemama-ocr-edited');
    if (storedRaw) setRawOcrText(storedRaw);
    if (storedEdited) setEditedText(storedEdited);
  }, []);

  useEffect(() => {
    sessionStorage.setItem('wisemama-ocr-raw', rawOcrText);
  }, [rawOcrText]);

  useEffect(() => {
    sessionStorage.setItem('wisemama-ocr-edited', editedText);
  }, [editedText]);

  useEffect(() => {
    if (!selectedLesson) return;
    setLessonTitle(selectedLesson.title || '');
    setDescription(selectedLesson.description || '');
    setNotes(selectedLesson.notes || '');
    setEditedText(selectedLesson.sourceText || '');
    setPinyinToggles(selectedLesson.pinyinToggles || {});
  }, [selectedLesson]);

  useEffect(() => {
    setPinyinToggles((prev) => {
      const next = { ...prev };
      for (const token of tokens) {
        if (!(token in next)) next[token] = true;
      }
      for (const key of Object.keys(next)) {
        if (!tokens.includes(key)) delete next[key];
      }
      return next;
    });
  }, [tokens]);

  const runOcr = async (files) => {
    if (!files?.length) return;
    setIsScanning(true);
    setError('');
    setStatus('OCR en cours...');

    const worker = await createWorker('chi_sim+chi_tra+eng');
    try {
      let allText = '';
      for (const file of files) {
        const { data } = await worker.recognize(file);
        allText += `\n${data?.text || ''}`;
      }
      const cleaned = keepChineseChars(allText);
      setRawOcrText(allText.trim());
      setEditedText(cleaned);
      setStatus('OCR termine. Verifie et corrige le texte.');
    } catch {
      setError('OCR impossible. Reessaie avec une image plus nette.');
      setStatus('');
    } finally {
      await worker.terminate();
      setIsScanning(false);
    }
  };

  const onFilesPicked = async (event) => {
    const fileList = Array.from(event.target.files || []);
    event.target.value = '';
    await runOcr(fileList);
  };

  const togglePinyin = (char) => {
    setPinyinToggles((prev) => ({ ...prev, [char]: !prev[char] }));
  };

  const generate = () => {
    const cleanTitle = lessonTitle.trim();
    if (!cleanTitle) {
      setError('Titre obligatoire.');
      return;
    }
    if (!tokens.length) {
      setError('Aucun caractere chinois detecte.');
      return;
    }

    const cards = generateLessonFlashcards({
      lessonId: selectedLessonId,
      sourceText: editedText,
      pinyinToggles,
      previousCards: selectedLesson?.cards || [],
    });
    const payload = {
      title: cleanTitle,
      description: description.trim(),
      sourceText: editedText.trim(),
      notes: notes.trim(),
      pinyinToggles,
      autoGenerated: true,
      cards,
    };

    if (selectedLessonId) {
      onUpdateLesson?.(selectedLessonId, payload);
      setStatus(`Lecon mise a jour: ${cards.length} fiches regenerees.`);
    } else {
      onCreateLesson?.(payload);
      setStatus(`Lecon creee: ${cards.length} fiches generees.`);
    }
    setError('');
    setSuccessTick((prev) => prev + 1);
    onSuccess?.();
  };

  return (
    <section className="ocr-builder" aria-label="OCR vers lecon">
      <div className="parent-panel-head">
        <h3>OCR {'->'} Lecon {'->'} Flashcards</h3>
        <TokenButton variant="ghost" className="ui-pressable" onClick={onClose}>
          Fermer
        </TokenButton>
      </div>
      <p className="parent-panel-subtitle">
        Scanne des pages, corrige le texte chinois, puis genere les fiches liees a la lecon.
      </p>

      <label className="lesson-field">
        <span>Mettre a jour une lecon existante (optionnel)</span>
        <select value={selectedLessonId} onChange={(e) => setSelectedLessonId(e.target.value)}>
          <option value="">Nouvelle lecon</option>
          {lessons.map((lesson) => (
            <option key={lesson.id} value={lesson.id}>
              {lesson.title}
            </option>
          ))}
        </select>
      </label>

      <div className="ocr-upload-row">
        <label className="ocr-upload-btn ui-pressable">
          <input type="file" accept="image/*" multiple onChange={onFilesPicked} disabled={isScanning} />
          {isScanning ? 'Scan OCR...' : 'Scanner / Importer images'}
        </label>
        <TokenButton
          variant="secondary"
          className="ui-pressable"
          onClick={() => {
            setRawOcrText('');
            setEditedText('');
            setPinyinToggles({});
            setStatus('');
            setError('');
          }}
        >
          Vider
        </TokenButton>
      </div>

      {status ? (
        <p className="ok-line wm-ok-line wm-success-pulse">
          {status}
          <SuccessBurst trigger={successTick} />
        </p>
      ) : null}
      {error ? <p className="error-line">{error}</p> : null}

      <div className="ocr-grid">
        <label className="lesson-field">
          <span>Texte OCR brut (temporaire)</span>
          <textarea value={rawOcrText} readOnly placeholder="Le resultat OCR brut apparait ici." />
        </label>
        <label className="lesson-field">
          <span>Texte lecon editable (chinois)</span>
          <textarea
            value={editedText}
            onChange={(e) => {
              setEditedText(keepChineseChars(e.target.value));
              setError('');
            }}
            placeholder="Corrige ici les caracteres, supprime le bruit OCR."
          />
        </label>
      </div>

      <div className="ocr-grid">
        <label className="lesson-field">
          <span>Titre de lecon *</span>
          <input
            value={lessonTitle}
            onChange={(e) => {
              setLessonTitle(e.target.value);
              setError('');
            }}
            placeholder="Ex: Lecon manuel chap. 3"
          />
        </label>
        <label className="lesson-field">
          <span>Description</span>
          <input
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Description courte"
          />
        </label>
      </div>

      <label className="lesson-field">
        <span>Notes parent (optionnel)</span>
        <textarea
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          placeholder="Conseils, exemples, contexte manuel..."
        />
      </label>

      <div className="ocr-char-panel">
        <div className="ocr-char-head">
          <strong>Toggle pinyin par caractere</strong>
          <span>{tokens.length} elements (mots/caracteres)</span>
        </div>
        <div className="ocr-char-list">
          {tokens.map((token) => (
            <button
              key={token}
              type="button"
              className={`ocr-char-chip ui-pressable ${pinyinToggles[token] ? 'active' : ''}`}
              onClick={() => togglePinyin(token)}
            >
              <span>{token}</span>
              <small>{pinyinToggles[token] ? 'Pinyin ON' : 'Pinyin OFF'}</small>
            </button>
          ))}
          {!tokens.length ? <p className="parent-empty">Aucun caractere detecte.</p> : null}
        </div>
      </div>

      <div className="parent-list-actions">
        <TokenButton className="ui-pressable" onClick={generate}>
          Generer les flashcards
        </TokenButton>
      </div>
    </section>
  );
}
