import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import defaultLessons from '../data/lessons.json';
import { getLessonsByOrder, normalizeLessonOrder } from '../utils/lessons/lessonOrder.js';

const lessonsStorageKey = 'wisemama-lessons-v1';
const lessonsStorageVersion = '2026-02-19-sync-v1';
const LessonsContext = createContext(null);

function safeString(value, fallback = '') {
  if (typeof value !== 'string') return fallback;
  return value;
}

function normalizeCard(card, index = 0) {
  const rawManual = card?.manualOverrides && typeof card.manualOverrides === 'object' ? card.manualOverrides : {};
  const rawTranslation = card?.translation && typeof card.translation === 'object' ? card.translation : {};
  const translationEn = safeString(rawTranslation.en, safeString(card?.english, ''));
  const translationFr = safeString(rawTranslation.fr, safeString(card?.french, ''));
  const relatedVocabulary = Array.isArray(card?.relatedVocabulary)
    ? card.relatedVocabulary.map((item) => safeString(item)).filter(Boolean)
    : [];
  const relatedWords = Array.isArray(card?.relatedWords)
    ? card.relatedWords
      .map((item) => ({
        hanzi: safeString(item?.hanzi),
        pinyin: safeString(item?.pinyin),
        en: safeString(item?.en),
      }))
      .filter((item) => item.hanzi)
    : relatedVocabulary.map((hanzi) => ({ hanzi, pinyin: '', en: '' }));
  const relatedVocabularyText = safeString(card?.relatedVocabularyText, relatedVocabulary.join(', '));
  return {
    id: safeString(card?.id, `card-${Date.now()}-${index}`),
    lessonId: safeString(card?.lessonId, ''),
    hanzi: safeString(card?.hanzi),
    pinyinEnabled: card?.pinyinEnabled !== false,
    pinyin: safeString(card?.pinyin),
    translation: {
      en: translationEn,
      fr: translationFr,
    },
    french: translationFr,
    english: translationEn,
    meanings: Array.isArray(card?.meanings) ? card.meanings.map((item) => safeString(item)).filter(Boolean) : [],
    classifiers: Array.isArray(card?.classifiers) ? card.classifiers.map((item) => safeString(item)).filter(Boolean) : [],
    partOfSpeech: safeString(card?.partOfSpeech, ''),
    exampleSentence: safeString(card?.exampleSentence, ''),
    notes: safeString(card?.notes, ''),
    relatedWords,
    relatedVocabulary,
    relatedVocabularyText,
    meta: {
      dictFound: card?.meta?.dictFound !== false,
    },
    manualOverrides: {
      pinyin: Boolean(rawManual.pinyin),
      french: Boolean(rawManual.french),
      english: Boolean(rawManual.english),
      exampleSentence: Boolean(rawManual.exampleSentence),
      relatedVocabulary: Boolean(rawManual.relatedVocabulary),
    },
    imageUrl: card?.imageUrl === null ? null : safeString(card?.imageUrl, null),
    audioUrl: card?.audioUrl === null ? null : safeString(card?.audioUrl, null),
  };
}

function normalizeLesson(lesson, index = 0) {
  const lessonId = safeString(lesson?.id, `lesson-${Date.now()}-${index}`);
  const cards = Array.isArray(lesson?.cards)
    ? lesson.cards.map((c, i) => normalizeCard({ ...c, lessonId: c?.lessonId || lessonId }, i))
    : [];
  const rawPinyinToggles = lesson?.pinyinToggles && typeof lesson.pinyinToggles === 'object'
    ? lesson.pinyinToggles
    : {};
  const pinyinToggles = Object.fromEntries(
    Object.entries(rawPinyinToggles).map(([key, value]) => [String(key), Boolean(value)]),
  );
  return {
    id: lessonId,
    globalLessonId: safeString(lesson?.globalLessonId, makeGlobalLessonId()),
    title: safeString(lesson?.title, `Lecon ${index + 1}`),
    order: normalizeLessonOrder(lesson?.order, index + 1),
    description: safeString(lesson?.description, ''),
    sourceText: safeString(lesson?.sourceText, ''),
    notes: safeString(lesson?.notes, ''),
    pinyinToggles,
    autoGenerated: Boolean(lesson?.autoGenerated),
    updatedAt: safeString(lesson?.updatedAt, ''),
    cards,
  };
}

function normalizeLessons(input) {
  if (!Array.isArray(input)) return [];
  return getLessonsByOrder(input.map((lesson, index) => normalizeLesson(lesson, index)));
}

function mergeBundledLessons(storedLessons, bundledLessons) {
  const normalizedStored = normalizeLessons(storedLessons);
  const normalizedBundled = normalizeLessons(bundledLessons);
  const storedById = new Map(normalizedStored.map((lesson) => [lesson.id, lesson]));
  const merged = [...normalizedStored];

  for (const bundledLesson of normalizedBundled) {
    const current = storedById.get(bundledLesson.id);
    if (!current) {
      merged.push(bundledLesson);
      storedById.set(bundledLesson.id, bundledLesson);
      continue;
    }

    const currentCardIds = new Set(current.cards.map((card) => card.id));
    const missingCards = bundledLesson.cards.filter((card) => !currentCardIds.has(card.id));
    if (missingCards.length === 0) continue;

    const updated = {
      ...current,
      cards: [...current.cards, ...missingCards],
    };
    const index = merged.findIndex((lesson) => lesson.id === current.id);
    if (index >= 0) merged[index] = updated;
    storedById.set(updated.id, updated);
  }

  return merged;
}

function makeLessonId() {
  return `lesson-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
}

function makeGlobalLessonId() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `glesson-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

function makeCardId() {
  return `card-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
}

function stampNow() {
  return new Date().toISOString();
}

function defaultCard() {
  return {
    id: makeCardId(),
    lessonId: '',
    hanzi: '',
    pinyinEnabled: true,
    pinyin: '',
    translation: {
      en: '',
      fr: '',
    },
    french: '',
    english: '',
    meanings: [],
    classifiers: [],
    partOfSpeech: '',
    exampleSentence: '',
    notes: '',
    relatedWords: [],
    relatedVocabulary: [],
    relatedVocabularyText: '',
    meta: {
      dictFound: true,
    },
    manualOverrides: {
      pinyin: false,
      french: false,
      english: false,
      exampleSentence: false,
      relatedVocabulary: false,
    },
    imageUrl: null,
    audioUrl: null,
  };
}

function getNextLessonOrder(lessons = []) {
  const max = lessons.reduce((currentMax, lesson) => {
    const order = normalizeLessonOrder(lesson?.order, 0);
    return Math.max(currentMax, order);
  }, 0);
  return max + 1;
}

export function LessonsProvider({ children }) {
  const [lessons, setLessons] = useState(() => normalizeLessons(defaultLessons));
  const [activeLessonId, setActiveLessonId] = useState(null);

  useEffect(() => {
    try {
      const stored = localStorage.getItem(lessonsStorageKey);
      if (!stored) {
        const normalized = normalizeLessons(defaultLessons);
        setLessons(normalized);
        setActiveLessonId(normalized[0]?.id || null);
        return;
      }
      const parsed = JSON.parse(stored);
      const storedLessons = Array.isArray(parsed) ? parsed : parsed?.lessons;
      const normalizedStored = normalizeLessons(storedLessons);
      const merged = mergeBundledLessons(normalizedStored, defaultLessons);
      if (merged.length > 0) {
        setLessons(merged);
        const storedActiveLessonId = typeof parsed?.activeLessonId === 'string' ? parsed.activeLessonId : '';
        const validActiveLessonId = merged.some((lesson) => lesson.id === storedActiveLessonId)
          ? storedActiveLessonId
          : merged[0]?.id || null;
        setActiveLessonId(validActiveLessonId);
      } else {
        const normalized = normalizeLessons(defaultLessons);
        setLessons(normalized);
        setActiveLessonId(normalized[0]?.id || null);
      }
    } catch {
      const normalized = normalizeLessons(defaultLessons);
      setLessons(normalized);
      setActiveLessonId(normalized[0]?.id || null);
    }
  }, []);

  useEffect(() => {
    if (!lessons.length) {
      if (activeLessonId !== null) setActiveLessonId(null);
      return;
    }
    const isValid = lessons.some((lesson) => lesson.id === activeLessonId);
    if (!isValid) {
      setActiveLessonId(lessons[0].id);
    }
  }, [activeLessonId, lessons]);

  useEffect(() => {
    try {
      localStorage.setItem(
        lessonsStorageKey,
        JSON.stringify({
          version: lessonsStorageVersion,
          lessons,
          activeLessonId,
        }),
      );
    } catch {
      // no-op
    }
  }, [activeLessonId, lessons]);

  const addLesson = () => {
    const nextOrder = getNextLessonOrder(lessons);
    const newLesson = {
      id: makeLessonId(),
      globalLessonId: makeGlobalLessonId(),
      title: 'Nouvelle lecon',
      order: nextOrder,
      description: '',
      updatedAt: stampNow(),
      cards: [defaultCard()],
    };
    setLessons((prev) => getLessonsByOrder([...prev, newLesson]));
    setActiveLessonId(newLesson.id);
    return newLesson.id;
  };

  const removeLesson = (lessonId) => {
    setLessons((prev) => prev.filter((lesson) => lesson.id !== lessonId));
  };

  const updateLessonTitle = (lessonId, title) => {
    setLessons((prev) =>
      prev.map((lesson) => (lesson.id === lessonId ? { ...lesson, title, updatedAt: stampNow() } : lesson)),
    );
  };

  const addCard = (lessonId) => {
    setLessons((prev) =>
      prev.map((lesson) =>
        lesson.id === lessonId
          ? {
              ...lesson,
              cards: [...lesson.cards, { ...defaultCard(), lessonId: lesson.id }],
              updatedAt: stampNow(),
            }
          : lesson,
      ),
    );
  };

  const removeCard = (lessonId, cardId) => {
    setLessons((prev) =>
      prev.map((lesson) => {
        if (lesson.id !== lessonId) return lesson;
        return { ...lesson, cards: lesson.cards.filter((card) => card.id !== cardId), updatedAt: stampNow() };
      }),
    );
  };

  const moveCard = (lessonId, cardId, direction) => {
    setLessons((prev) =>
      prev.map((lesson) => {
        if (lesson.id !== lessonId) return lesson;
        const idx = lesson.cards.findIndex((card) => card.id === cardId);
        if (idx < 0) return lesson;
        const target = direction === 'up' ? idx - 1 : idx + 1;
        if (target < 0 || target >= lesson.cards.length) return lesson;
        const nextCards = [...lesson.cards];
        const [item] = nextCards.splice(idx, 1);
        nextCards.splice(target, 0, item);
        return { ...lesson, cards: nextCards, updatedAt: stampNow() };
      }),
    );
  };

  const updateCard = (lessonId, cardId, patch) => {
    setLessons((prev) =>
      prev.map((lesson) => {
        if (lesson.id !== lessonId) return lesson;
        return {
          ...lesson,
          updatedAt: stampNow(),
          cards: lesson.cards.map((card) => (card.id === cardId ? { ...card, ...patch } : card)),
        };
      }),
    );
  };

  const createLesson = ({
    title = 'Nouvelle lecon',
    order,
    description = '',
    cards = [defaultCard()],
    sourceText = '',
    notes = '',
    pinyinToggles = {},
    autoGenerated = false,
  } = {}) => {
    const nextOrder = normalizeLessonOrder(order, getNextLessonOrder(lessons));
    const lesson = normalizeLesson(
      {
        id: makeLessonId(),
        globalLessonId: makeGlobalLessonId(),
        title,
        order: nextOrder,
        description,
        sourceText,
        notes,
        pinyinToggles,
        autoGenerated,
        updatedAt: stampNow(),
        cards,
      },
      0,
    );
    lesson.cards = lesson.cards.map((card) => ({ ...card, lessonId: lesson.id }));
    setLessons((prev) => getLessonsByOrder([...prev, lesson]));
    setActiveLessonId(lesson.id);
    return lesson;
  };

  const updateLesson = (lessonId, patch = {}) => {
    setLessons((prev) =>
      getLessonsByOrder(prev.map((lesson) => {
        if (lesson.id !== lessonId) return lesson;
        const merged = { ...lesson, ...patch, updatedAt: stampNow() };
        merged.order = normalizeLessonOrder(merged.order, lesson.order || 1);
        if (Array.isArray(merged.cards)) {
          merged.cards = merged.cards.map((card, idx) =>
            normalizeCard({ ...card, lessonId: lessonId }, idx),
          );
        }
        return merged;
      })),
    );
  };

  const duplicateLesson = (lessonId) => {
    let duplicated = null;
    setLessons((prev) => {
      const source = prev.find((lesson) => lesson.id === lessonId);
      if (!source) return prev;
      const nextOrder = getNextLessonOrder(prev);
      duplicated = normalizeLesson(
        {
          ...source,
          id: makeLessonId(),
          globalLessonId: makeGlobalLessonId(),
          order: nextOrder,
          title: `${source.title} (Copy)`,
          updatedAt: stampNow(),
          cards: source.cards.map((card) => ({
            ...card,
            id: makeCardId(),
          })),
        },
        0,
      );
      duplicated.cards = duplicated.cards.map((card) => ({ ...card, lessonId: duplicated.id }));
      return getLessonsByOrder([...prev, duplicated]);
    });
    if (duplicated?.id) setActiveLessonId(duplicated.id);
    return duplicated;
  };

  const replaceLessons = (payload) => {
    const normalized = normalizeLessons(payload);
    if (normalized.length === 0) {
      throw new Error('invalid_lessons');
    }
    setLessons(normalized);
    setActiveLessonId((prev) => (normalized.some((lesson) => lesson.id === prev) ? prev : normalized[0]?.id || null));
  };

  const resetLessonsToDefault = () => {
    const normalized = normalizeLessons(defaultLessons);
    setLessons(normalized);
    setActiveLessonId(normalized[0]?.id || null);
  };

  const setActiveLesson = (lessonId) => {
    const nextId = typeof lessonId === 'string' ? lessonId : '';
    if (!nextId) return;
    if (!lessons.some((lesson) => lesson.id === nextId)) return;
    setActiveLessonId(nextId);
  };

  const getActiveLesson = () => lessons.find((lesson) => lesson.id === activeLessonId) || null;

  const ensureActiveLesson = () => {
    if (activeLessonId && lessons.some((lesson) => lesson.id === activeLessonId)) return activeLessonId;
    if (lessons.length === 0) return null;
    const firstId = lessons[0].id;
    setActiveLessonId(firstId);
    return firstId;
  };

  const value = useMemo(
    () => ({
      lessons,
      activeLessonId,
      addLesson,
      createLesson,
      removeLesson,
      updateLesson,
      duplicateLesson,
      updateLessonTitle,
      addCard,
      removeCard,
      moveCard,
      updateCard,
      replaceLessons,
      resetLessonsToDefault,
      setActiveLesson,
      getActiveLesson,
      ensureActiveLesson,
    }),
    [activeLessonId, lessons],
  );

  return <LessonsContext.Provider value={value}>{children}</LessonsContext.Provider>;
}

export function useLessons() {
  const ctx = useContext(LessonsContext);
  if (!ctx) {
    throw new Error('useLessons must be used inside LessonsProvider');
  }
  return ctx;
}
