import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import defaultLessons from '../data/lessons.json';
import { getLessonsByOrder, normalizeLessonOrder } from '../utils/lessons/lessonOrder.js';
import {
  getAllLessons as getAllLessonsV2,
  createLesson as createLessonV2,
  updateLesson as updateLessonV2,
  deleteLesson as deleteLessonV2,
  duplicateLesson as duplicateLessonV2,
} from '../utils/database/lessonDB.js';
import {
  getCharacter,
  upsertCharacter,
} from '../utils/database/characterDB.js';
import { migrateFromLocalStorageV1, migrateLessonsV1ToV2 } from '../utils/database/migration.js';

const lessonsStorageKey = 'wisemama-lessons-ui-v2';
const lessonsStorageVersion = '2026-03-11-v2-ui';
const LessonsContext = createContext(null);

function safeString(value, fallback = '') {
  if (typeof value !== 'string') return fallback;
  return value;
}

function normalizeCard(card, index = 0) {
  const rawManual = card?.manualOverrides && typeof card.manualOverrides === 'object' ? card.manualOverrides : {};
  const rawTranslation = card?.translation && typeof card.translation === 'object' ? card.translation : {};
  const translationEn = safeString(rawTranslation.en, safeString(card?.english, ''));
  const translationFr = safeString(rawTranslation.fr, safeString(card?.french, ''));
  const relatedVocabulary = Array.isArray(card?.relatedVocabulary)
    ? card.relatedVocabulary.map((item) => safeString(item)).filter(Boolean)
    : [];
  const relatedWords = Array.isArray(card?.relatedWords)
    ? card.relatedWords
      .map((item) => ({
        hanzi: safeString(item?.hanzi),
        pinyin: safeString(item?.pinyin),
        en: safeString(item?.en),
      }))
      .filter((item) => item.hanzi)
    : relatedVocabulary.map((hanzi) => ({ hanzi, pinyin: '', en: '' }));
  const relatedVocabularyText = safeString(card?.relatedVocabularyText, relatedVocabulary.join(', '));
  return {
    id: safeString(card?.id, `card-${Date.now()}-${index}`),
    lessonId: safeString(card?.lessonId, ''),
    hanzi: safeString(card?.hanzi),
    pinyinEnabled: card?.pinyinEnabled !== false,
    pinyin: safeString(card?.pinyin),
    translation: {
      en: translationEn,
      fr: translationFr,
    },
    french: translationFr,
    english: translationEn,
    meanings: Array.isArray(card?.meanings) ? card.meanings.map((item) => safeString(item)).filter(Boolean) : [],
    classifiers: Array.isArray(card?.classifiers) ? card.classifiers.map((item) => safeString(item)).filter(Boolean) : [],
    partOfSpeech: safeString(card?.partOfSpeech, ''),
    exampleSentence: safeString(card?.exampleSentence, ''),
    notes: safeString(card?.notes, ''),
    relatedWords,
    relatedVocabulary,
    relatedVocabularyText,
    meta: {
      dictFound: card?.meta?.dictFound !== false,
    },
    manualOverrides: {
      pinyin: Boolean(rawManual.pinyin),
      french: Boolean(rawManual.french),
      english: Boolean(rawManual.english),
      exampleSentence: Boolean(rawManual.exampleSentence),
      relatedVocabulary: Boolean(rawManual.relatedVocabulary),
    },
    imageUrl: card?.imageUrl === null ? null : safeString(card?.imageUrl, null),
    audioUrl: card?.audioUrl === null ? null : safeString(card?.audioUrl, null),
  };
}

function normalizeLesson(lesson, index = 0) {
  const lessonId = safeString(lesson?.id, `lesson-${Date.now()}-${index}`);
  const cards = Array.isArray(lesson?.cards)
    ? lesson.cards.map((c, i) => normalizeCard({ ...c, lessonId: c?.lessonId || lessonId }, i))
    : [];
  const rawPinyinToggles = lesson?.pinyinToggles && typeof lesson.pinyinToggles === 'object'
    ? lesson.pinyinToggles
    : {};
  const pinyinToggles = Object.fromEntries(
    Object.entries(rawPinyinToggles).map(([key, value]) => [String(key), Boolean(value)]),
  );
  return {
    id: lessonId,
    globalLessonId: safeString(lesson?.globalLessonId, makeGlobalLessonId()),
    title: safeString(lesson?.title, `Lecon ${index + 1}`),
    order: normalizeLessonOrder(lesson?.order, index + 1),
    description: safeString(lesson?.description, ''),
    sourceText: safeString(lesson?.sourceText, ''),
    notes: safeString(lesson?.notes, ''),
    pinyinToggles,
    autoGenerated: Boolean(lesson?.autoGenerated),
    updatedAt: safeString(lesson?.updatedAt, ''),
    cards,
  };
}

function normalizeLessons(input) {
  if (!Array.isArray(input)) return [];
  return getLessonsByOrder(input.map((lesson, index) => normalizeLesson(lesson, index)));
}

function getPrimaryAudioUrl(char) {
  if (!char?.audioRecordings?.length) return null;
  const primary = char.audioRecordings.find((item) => item.isPrimary);
  return primary?.url || char.audioRecordings[0]?.url || null;
}

function getPrimaryImageUrl(char) {
  if (!char?.images?.length) return null;
  return char.images[0]?.url || null;
}

function expandLessonFromV2(lesson) {
  const cardMap = lesson?.cardMap && typeof lesson.cardMap === 'object' ? lesson.cardMap : {};
  const characterRefs = Array.isArray(lesson?.characterRefs) ? lesson.characterRefs : [];
  const cards = characterRefs.map((hanzi, index) => {
    const char = getCharacter(hanzi) || {};
    const id = cardMap[hanzi] || `card-${lesson.id}-${index}`;
    const translationEn = safeString(char?.english, safeString(char?.translation?.en, ''));
    const translationFr = safeString(char?.french, safeString(char?.translation?.fr, ''));
    const relatedWords = Array.isArray(char?.relatedWords)
      ? char.relatedWords.map((item) => ({
        hanzi: safeString(item?.word),
        pinyin: safeString(item?.pinyin),
        en: safeString(item?.definition),
      }))
      : [];
    return normalizeCard(
      {
        id,
        lessonId: lesson.id,
        hanzi,
        pinyin: safeString(char?.pinyin, ''),
        french: translationFr,
        english: translationEn,
        translation: { en: translationEn, fr: translationFr },
        relatedWords,
        audioUrl: getPrimaryAudioUrl(char),
        imageUrl: getPrimaryImageUrl(char),
      },
      index,
    );
  });
  return normalizeLesson(
    {
      ...lesson,
      cards,
      updatedAt: lesson?.lastUpdated || lesson?.updatedAt || '',
    },
    0,
  );
}

function extractUniqueChars(text = '') {
  const seen = new Set();
  const ordered = [];
  for (const char of Array.from(String(text || ''))) {
    if (!/[\u3400-\u9fff\uf900-\ufaff]/u.test(char)) continue;
    if (seen.has(char)) continue;
    seen.add(char);
    ordered.push(char);
  }
  return ordered;
}

function buildCharacterRefsFromCards(cards = []) {
  const ordered = [];
  cards.forEach((card) => {
    const hanzi = String(card?.hanzi || '');
    if (!hanzi) return;
    extractUniqueChars(hanzi).forEach((char) => {
      if (!ordered.includes(char)) ordered.push(char);
    });
  });
  return ordered;
}

function buildCardMapFromCards(cards = []) {
  const map = {};
  cards.forEach((card) => {
    const hanzi = String(card?.hanzi || '');
    if (!hanzi || !card?.id) return;
    extractUniqueChars(hanzi).forEach((char) => {
      if (!map[char]) map[char] = String(card.id);
    });
  });
  return map;
}

function upsertCharacterFromCard(card, lessonId) {
  const hanzi = String(card?.hanzi || '');
  if (!hanzi) return;
  const chars = extractUniqueChars(hanzi);
  chars.forEach((char) => {
    const existing = getCharacter(char);
    const appears = new Set(existing?.appearsInLessons || []);
    appears.add(lessonId);
    const updates = {
      pinyin: safeString(card?.pinyin, existing?.pinyin || ''),
      pinyinNumbered: safeString(card?.pinyin, existing?.pinyinNumbered || ''),
      french: safeString(card?.french || card?.translation?.fr, existing?.french || ''),
      english: safeString(card?.english || card?.translation?.en, existing?.english || ''),
      appearsInLessons: Array.from(appears),
      firstSeenLesson: existing?.firstSeenLesson || lessonId,
      firstSeenDate: existing?.firstSeenDate || new Date().toISOString(),
      relatedWords: Array.isArray(card?.relatedWords)
        ? card.relatedWords.map((item) => ({
          word: safeString(item?.hanzi),
          pinyin: safeString(item?.pinyin),
          definition: safeString(item?.en),
        }))
        : existing?.relatedWords || [],
    };
    if (card?.audioUrl) {
      updates.audioRecordings = [
        {
          id: `audio-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          url: card.audioUrl,
          recordedBy: 'import',
          recordedByProfile: '',
          recordedDate: new Date().toISOString(),
          duration: 0,
          isPrimary: true,
          quality: 'good',
        },
      ];
    }
    if (card?.imageUrl) {
      updates.images = [
        {
          id: `img-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          url: card.imageUrl,
          source: 'upload',
          uploadedDate: new Date().toISOString(),
        },
      ];
    }
    upsertCharacter(char, updates);
  });
}

function makeLessonId() {
  return `lesson-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
}

function makeGlobalLessonId() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `glesson-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

function makeCardId() {
  return `card-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`;
}

function stampNow() {
  return new Date().toISOString();
}

function defaultCard() {
  return {
    id: makeCardId(),
    lessonId: '',
    hanzi: '',
    pinyinEnabled: true,
    pinyin: '',
    translation: {
      en: '',
      fr: '',
    },
    french: '',
    english: '',
    meanings: [],
    classifiers: [],
    partOfSpeech: '',
    exampleSentence: '',
    notes: '',
    relatedWords: [],
    relatedVocabulary: [],
    relatedVocabularyText: '',
    meta: {
      dictFound: true,
    },
    manualOverrides: {
      pinyin: false,
      french: false,
      english: false,
      exampleSentence: false,
      relatedVocabulary: false,
    },
    imageUrl: null,
    audioUrl: null,
  };
}

function getNextLessonOrder(lessons = []) {
  const max = lessons.reduce((currentMax, lesson) => {
    const order = normalizeLessonOrder(lesson?.order, 0);
    return Math.max(currentMax, order);
  }, 0);
  return max + 1;
}

export function LessonsProvider({ children }) {
  const [lessons, setLessons] = useState(() => []);
  const [activeLessonId, setActiveLessonId] = useState(null);

  useEffect(() => {
    const initializeFromV2 = () => {
      const v2Lessons = getAllLessonsV2();
      if (!v2Lessons.length) {
        const migrated = migrateFromLocalStorageV1({ reset: true });
        if (!migrated?.ok) {
          migrateLessonsV1ToV2(defaultLessons, { reset: true });
        }
      }
      const refreshed = getAllLessonsV2().map((lesson) => expandLessonFromV2(lesson));
      setLessons(getLessonsByOrder(refreshed));
    };

    try {
      const stored = localStorage.getItem(lessonsStorageKey);
      const parsed = stored ? JSON.parse(stored) : null;
      initializeFromV2();
      const storedActiveLessonId = typeof parsed?.activeLessonId === 'string' ? parsed.activeLessonId : '';
      if (storedActiveLessonId) {
        setActiveLessonId(storedActiveLessonId);
      } else {
        const initial = getAllLessonsV2()[0];
        setActiveLessonId(initial?.id || null);
      }
    } catch {
      migrateLessonsV1ToV2(defaultLessons, { reset: true });
      const refreshed = getAllLessonsV2().map((lesson) => expandLessonFromV2(lesson));
      setLessons(getLessonsByOrder(refreshed));
      setActiveLessonId(refreshed[0]?.id || null);
    }
  }, []);

  useEffect(() => {
    if (!lessons.length) {
      if (activeLessonId !== null) setActiveLessonId(null);
      return;
    }
    const isValid = lessons.some((lesson) => lesson.id === activeLessonId);
    if (!isValid) {
      setActiveLessonId(lessons[0].id);
    }
  }, [activeLessonId, lessons]);

  useEffect(() => {
    try {
      localStorage.setItem(
        lessonsStorageKey,
        JSON.stringify({
          version: lessonsStorageVersion,
          activeLessonId,
        }),
      );
    } catch {
      // no-op
    }
  }, [activeLessonId, lessons]);

  const addLesson = () => {
    const nextOrder = getNextLessonOrder(lessons);
    const lesson = createLessonV2({
      title: 'Nouvelle lecon',
      order: nextOrder,
      characterRefs: [],
      notes: '',
    });
    const expanded = expandLessonFromV2(lesson);
    setLessons((prev) => getLessonsByOrder([...prev, expanded]));
    setActiveLessonId(lesson.id);
    return lesson.id;
  };

  const removeLesson = (lessonId) => {
    deleteLessonV2(lessonId);
    const refreshed = getAllLessonsV2().map((lesson) => expandLessonFromV2(lesson));
    setLessons(getLessonsByOrder(refreshed));
  };

  const updateLessonTitle = (lessonId, title) => {
    updateLessonV2(lessonId, { title, lastUpdated: stampNow() });
    const refreshed = getAllLessonsV2().map((lesson) => expandLessonFromV2(lesson));
    setLessons(getLessonsByOrder(refreshed));
  };

  const addCard = (lessonId) => {
    setLessons((prev) =>
      prev.map((lesson) =>
        lesson.id === lessonId
          ? {
              ...lesson,
              cards: [...lesson.cards, { ...defaultCard(), lessonId: lesson.id }],
              updatedAt: stampNow(),
            }
          : lesson,
      ),
    );
  };

  const removeCard = (lessonId, cardId) => {
    setLessons((prev) =>
      prev.map((lesson) => {
        if (lesson.id !== lessonId) return lesson;
        return { ...lesson, cards: lesson.cards.filter((card) => card.id !== cardId), updatedAt: stampNow() };
      }),
    );
  };

  const moveCard = (lessonId, cardId, direction) => {
    setLessons((prev) =>
      prev.map((lesson) => {
        if (lesson.id !== lessonId) return lesson;
        const idx = lesson.cards.findIndex((card) => card.id === cardId);
        if (idx < 0) return lesson;
        const target = direction === 'up' ? idx - 1 : idx + 1;
        if (target < 0 || target >= lesson.cards.length) return lesson;
        const nextCards = [...lesson.cards];
        const [item] = nextCards.splice(idx, 1);
        nextCards.splice(target, 0, item);
        return { ...lesson, cards: nextCards, updatedAt: stampNow() };
      }),
    );
  };

  const updateCard = (lessonId, cardId, patch) => {
    setLessons((prev) =>
      prev.map((lesson) => {
        if (lesson.id !== lessonId) return lesson;
        return {
          ...lesson,
          updatedAt: stampNow(),
          cards: lesson.cards.map((card) => (card.id === cardId ? { ...card, ...patch } : card)),
        };
      }),
    );
  };

  const createLesson = ({
    title = 'Nouvelle lecon',
    order,
    description = '',
    cards = [defaultCard()],
    sourceText = '',
    notes = '',
    pinyinToggles = {},
    autoGenerated = false,
  } = {}) => {
    const nextOrder = normalizeLessonOrder(order, getNextLessonOrder(lessons));
    const cardMap = buildCardMapFromCards(cards);
    const characterRefs = buildCharacterRefsFromCards(cards);
    const lesson = createLessonV2({
      title,
      order: nextOrder,
      description,
      sourceText,
      notes,
      characterRefs,
      cardMap,
      pinyinToggles,
      autoGenerated,
    });
    cards.forEach((card) => upsertCharacterFromCard(card, lesson.id));
    const refreshed = getAllLessonsV2().map((item) => expandLessonFromV2(item));
    setLessons(getLessonsByOrder(refreshed));
    setActiveLessonId(lesson.id);
    return expandLessonFromV2(lesson);
  };

  const updateLesson = (lessonId, patch = {}) => {
    const nextOrder = normalizeLessonOrder(patch?.order, undefined);
    const cards = Array.isArray(patch?.cards) ? patch.cards : null;
    const cardMap = cards ? buildCardMapFromCards(cards) : undefined;
    const characterRefs = cards ? buildCharacterRefsFromCards(cards) : undefined;
    const updates = {
      ...patch,
      ...(nextOrder ? { order: nextOrder } : {}),
      ...(characterRefs ? { characterRefs } : {}),
      ...(cardMap ? { cardMap } : {}),
      lastUpdated: stampNow(),
    };
    updateLessonV2(lessonId, updates);
    if (cards) {
      cards.forEach((card) => upsertCharacterFromCard(card, lessonId));
    }
    const refreshed = getAllLessonsV2().map((lesson) => expandLessonFromV2(lesson));
    setLessons(getLessonsByOrder(refreshed));
  };

  const duplicateLesson = (lessonId) => {
    const duplicated = duplicateLessonV2(lessonId);
    if (!duplicated) return null;
    const refreshed = getAllLessonsV2().map((lesson) => expandLessonFromV2(lesson));
    setLessons(getLessonsByOrder(refreshed));
    setActiveLessonId(duplicated.id);
    return expandLessonFromV2(duplicated);
  };

  const replaceLessons = (payload) => {
    if (!Array.isArray(payload) || payload.length === 0) {
      throw new Error('invalid_lessons');
    }
    migrateLessonsV1ToV2(payload, { reset: true });
    const refreshed = getAllLessonsV2().map((lesson) => expandLessonFromV2(lesson));
    setLessons(getLessonsByOrder(refreshed));
    setActiveLessonId((prev) => (refreshed.some((lesson) => lesson.id === prev) ? prev : refreshed[0]?.id || null));
  };

  const resetLessonsToDefault = () => {
    migrateLessonsV1ToV2(defaultLessons, { reset: true });
    const refreshed = getAllLessonsV2().map((lesson) => expandLessonFromV2(lesson));
    setLessons(getLessonsByOrder(refreshed));
    setActiveLessonId(refreshed[0]?.id || null);
  };

  const setActiveLesson = (lessonId) => {
    const nextId = typeof lessonId === 'string' ? lessonId : '';
    if (!nextId) return;
    if (!lessons.some((lesson) => lesson.id === nextId)) return;
    setActiveLessonId(nextId);
  };

  const getActiveLesson = () => lessons.find((lesson) => lesson.id === activeLessonId) || null;

  const ensureActiveLesson = () => {
    if (activeLessonId && lessons.some((lesson) => lesson.id === activeLessonId)) return activeLessonId;
    if (lessons.length === 0) return null;
    const firstId = lessons[0].id;
    setActiveLessonId(firstId);
    return firstId;
  };

  const value = useMemo(
    () => ({
      lessons,
      activeLessonId,
      addLesson,
      createLesson,
      removeLesson,
      updateLesson,
      duplicateLesson,
      updateLessonTitle,
      addCard,
      removeCard,
      moveCard,
      updateCard,
      replaceLessons,
      resetLessonsToDefault,
      setActiveLesson,
      getActiveLesson,
      ensureActiveLesson,
    }),
    [activeLessonId, lessons],
  );

  return <LessonsContext.Provider value={value}>{children}</LessonsContext.Provider>;
}

export function useLessons() {
  const ctx = useContext(LessonsContext);
  if (!ctx) {
    throw new Error('useLessons must be used inside LessonsProvider');
  }
  return ctx;
}
